config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#index'

  resource :dashboard, only: [] do
    get :sample
  end

  resources :costs, except: :show
  resources :cost_categories, except: :show
  resources :funds, except: :show
  resources :incomes, except: :show

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :charts, only: [] do
        collection do
          get :bar_month_by_category, :area_last_days_costs, :donut_category_by_last
        end
      end
    end
  end

  namespace :kodi do
    namespace :v1 do
      resources :videos, only: [:index, :show] do
        get :search, :root_directory, on: :collection
      end
    end
  end

  namespace :react do
    namespace :v1 do
      resources :audios, only: [:index] do
        get :seed, on: :collection
      end

      resources :users, only: [] do
        get :current, on: :collection
      end
    end
  end

  ActiveAdmin.routes(self)
end

app/views/shared/_navbar_dropdown_fund_changes.html.haml
%li.dropdown
  %a.dropdown-toggle{ 'data-toggle' => 'dropdown', href: '#' }
    %i.fa.fa-credit-card.fa-fw 
    %i.fa.fa-caret-down

  %ul.dropdown-menu.dropdown-messages
    - NavbarDropdownPresenter.fund_changes.each do |change|
      %li
        %a{ href: '#' }
          %div
            %strong= change.fund.name
            %span.pull-right.text-muted
              %em= l(change.created_at.to_date)
          %div= t(:fund_changed_form_to, from: "#{change.from} #{change.fund.currency}", to: "#{change.to} #{change.fund.currency}")
      %li.divider
    %li
      = link_to funds_path, class: 'text-center' do
        %strong= t(:funds_list)
        %i.fa.fa-angle-right

app/views/shared/_navbar_dropdown_month_limits.html.haml
%li.dropdown
  %a.dropdown-toggle{ 'data-toggle' => 'dropdown', href: '#' }
    %i.fa.fa-tasks.fa-fw
    %i.fa.fa-caret-down
  %ul.dropdown-menu.dropdown-tasks
    - CostCategoryPresenter.month_limits(4).each do |limit|
      %li
        %a{ href: '#' }
          %div
            %p
              %strong= limit[:name]
              %span.text-muted
                = "#{limit[:progress]}%"
                = "(#{t(:spent_amount_limit, amount: limit[:month_amount], limit: limit[:month_limit])})"
            .progress.progress-striped.active
              .progress-bar{ class: progress_bar_class(limit[:progress]), role: 'progressbar', 'aria-valuenow' => limit[:progress], 'aria-valuemin' => 0, 'aria-valuemax' => 100, style: "width: #{limit[:progress]}%" }
                %span
                  = "#{limit[:progress]}%"
                  = "(#{t(:spent_amount_limit, amount: limit[:month_amount], limit: limit[:month_limit])})"
      %li.divider
    %li
      = link_to cost_categories_path, class: 'text-center' do
        %strong= t(:cost_categories_list)
        %i.fa.fa-angle-right

app/views/shared/_navbar_static_side.html.haml
.navbar-default.sidebar{ role: 'navigation' }
  .sidebar-nav.navbar-collapse.collapse
    %ul#side-menu.nav
      %li.sidebar-search
        .input-group.custom-search-form
          %input.form-control{ type: "text", placeholder: "Search..." }
          %span.input-group-btn
            %button.btn.btn-default{ type: "button" }
              %i.fa.fa-search
      %li
        %a{ href: '/' }
          %i.fa.fa-dashboard.fa-fw
          = t(:dashboard)
      %li
        %a{ href: '#' }
          %i.fa.fa-money.fa-fw
          = t(:costs)
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to t(:costs_list), costs_path
          %li
            = link_to t(:add_new_cost), new_cost_path
      %li
        %a{ href: '#' }
          %i.fa.fa-th-list.fa-fw
          = t(:cost_categories)
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to t(:cost_categories_list), cost_categories_path
          %li
            = link_to t(:add_new_cost_category), new_cost_category_path
      %li
        %a{ href: '#' }
          %i.fa.fa-credit-card.fa-fw
          = t(:funds)
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to t(:funds_list), funds_path
          %li
            = link_to t(:add_new_fund), new_fund_path
      %li
        %a{ href: '#' }
          %i.fa.fa-download.fa-fw
          = t(:incomes)
          %span.fa.arrow
        %ul.nav.nav-second-level
          %li
            = link_to t(:incomes_list), incomes_path
          %li
            = link_to t(:add_new_income), new_income_path
      %li
        %a{ href: '/dashboard/sample' }
          %i.fa.fa-camera.fa-fw
          | Sample Dashboard

app/views/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">FBudget</a>
  </div>
  <!-- /.navbar-header -->

  <ul class="nav navbar-top-links navbar-right">

    <% cache 'fund_change.shared.navbar_dropdown_fund_changes' do %>
      <%= render 'shared/navbar_dropdown_fund_changes' %>
    <% end %>
    <% cache 'last_cost.shared.navbar_dropdown_month_limits' do %>
      <%= render 'shared/navbar_dropdown_month_limits' %>
    <% end %>

    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-alerts">
        <li>
          <a href="#">
            <div>
              <i class="fa fa-comment fa-fw"></i> New Comment
              <span class="pull-right text-muted small">4 minutes ago</span>
            </div>
          </a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="#">
            <div>
              <i class="fa fa-twitter fa-fw"></i> 3 New Followers
              <span class="pull-right text-muted small">12 minutes ago</span>
            </div>
          </a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="#">
            <div>
              <i class="fa fa-envelope fa-fw"></i> Message Sent
              <span class="pull-right text-muted small">4 minutes ago</span>
            </div>
          </a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="#">
            <div>
              <i class="fa fa-tasks fa-fw"></i> New Task
              <span class="pull-right text-muted small">4 minutes ago</span>
            </div>
          </a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="#">
            <div>
              <i class="fa fa-upload fa-fw"></i> Server Rebooted
              <span class="pull-right text-muted small">4 minutes ago</span>
            </div>
          </a>
        </li>
        <li class="divider"></li>
        <li>
          <a class="text-center" href="#">
            <strong>See All Alerts</strong>
            <i class="fa fa-angle-right"></i>
          </a>
        </li>
      </ul>
      <!-- /.dropdown-alerts -->
    </li>
    <!-- /.dropdown -->
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu dropdown-user">
        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
        </li>
        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out fa-fw"></i> Logout
          <% end %>
        </li>
      </ul>
      <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
  </ul>
  <!-- /.navbar-top-links -->

  <%= render 'shared/navbar_static_side' %>
</nav>