config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#index'

  resource :dashboard, only: [] do
    get :sample
  end

  resources :costs, except: :show
  resources :cost_categories, except: :show
  resources :funds, except: :show
  resources :incomes, except: :show

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :charts, only: [] do
        collection do
          get :bar_month_by_category, :area_last_days_costs, :donut_category_by_last
        end
      end
    end
  end

  namespace :kodi do
    namespace :v1 do
      resources :videos, only: [:index, :show] do
        get :search, :root_directory, on: :collection
      end
    end
  end

  namespace :react do
    namespace :v1 do
      resources :audios, only: [:index] do
        get :seed, on: :collection
      end

      resources :users, only: [] do
        get :current, on: :collection
      end
    end
  end

  ActiveAdmin.routes(self)
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :user
  belongs_to :cost_category

  validates_presence_of :name, :cost_category_id, :amount
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  after_action :expire_last_cost_fragments, only: [:create, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @cost_query = CostQuery.perform(params)
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params.merge(user: current_user))

    respond_to do |format|
      if cost.save
        format.html { redirect_to costs_url, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: cost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if cost.update(cost_params)
        format.html { redirect_to costs_url, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: cost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  private def cost
    @cost ||= Cost.find(params[:id])
  end
  helper_method :cost

  # Never trust parameters from the scary internet, only allow the white list through.
  private def cost_params
    params.require(:cost).permit(
      :cost_category_id,
      :name,
      :amount,
      :description,
      :spent_on
    )
  end
end

app/views/costs/_filter_form.html.haml
.panel.panel-info
  .panel-heading
    = t(:filters)
  .panel-body
    = simple_form_for cost_query, as: :cost, method: :get, url: costs_path, defaults: { input_html: { class: 'form-control' }, required: false } do |f|
      .row
        .col-lg-6.slide-toggle-box
          .toggle-action.show{ class: "#{cost_query.any_filter? ? 'hidden' : ''}"}
            %button.btn.btn-default
              %i.fa.fa-bar-chart-o.fa-fw
              = t(:show_filters)
          .toggle-content{ class: "#{cost_query.any_filter? ? '' : 'hidden'}"}
            - if cost_query.any_filter?
              .alert.alert-success
                = t(:filters_total_count, total_count: cost_query.total_count).html_safe
                %br
                = t(:filters_sum_amount, sum_amount: cost_query.sum_amount).html_safe
            %fieldset
              = f.input :name
              = f.input :cost_category_id,
                collection: cost_categories,
                prompt: :translate
              = f.input :amount_from, as: :integer
              = f.input :amount_to, as: :integer
              = f.input :spent_on_from, as: :date, html5: true, input_html: { value: cost_query.spent_on_from }
              = f.input :spent_on_to, as: :date, html5: true, input_html: { value: cost_query.spent_on_to }
            .actions
              = f.submit t(:to_filter), class: 'btn btn-success'
              = link_to costs_path, class: 'btn btn-warning' do
                %i.fa.fa-minus
                = t(:reset)
              %span.toggle-action
                %button.btn.btn-default
                  %i.fa.fa-bar-chart-o.fa-fw
                  = t(:hide_filters)

:javascript
  $('.slide-toggle-box .toggle-action').on('click', function(e) {
    e.preventDefault();
    var box = $(e.currentTarget).parents('.slide-toggle-box');
    box.find('.toggle-content, .toggle-action.show').toggleClass('hidden');
  });

app/views/costs/_form.html.haml
= simple_form_for cost, defaults: { input_html: { class: 'form-control' } } do |f|
  .row
    .col-lg-6
      = f.error_notification
      %fieldset
        = f.input :name
        = f.input :cost_category_id, collection: cost_categories, prompt: :translate
        = f.input :amount
        .slide-toggle-box
          .toggle-action.show.form-group
            = link_to t(:show_additional_fields), '#'
          .toggle-content.hidden
            = f.input :description
            = f.input :spent_on
            .toggle-action.form-group
              = link_to t(:hide_additional_fields), '#'
      .actions
        = f.submit t(:save), class: 'btn btn-success'

:javascript
  $('.slide-toggle-box .toggle-action').on('click', function(e) {
    e.preventDefault();
    var box = $(e.currentTarget).parents('.slide-toggle-box');
    box.find('.toggle-content, .toggle-action.show').toggleClass('hidden');
  });

app/views/costs/edit.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:edit_cost)
.row
  .col-lg-12
    = render 'form'

app/views/costs/index.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:costs)
.row.hidden-xs
  .col-lg-12
    %p.pull-right
      = link_to new_cost_path, class: 'btn btn-success' do
        %i.fa.fa-plus
        = t(:add_new_cost)
.row
  .col-lg-12
    = render 'filter_form', cost_query: @cost_query

    .panel.panel-default
      .panel-heading= t(:costs_list)
      .panel-body
        .table-responsive
          %table.table
            %thead
              %tr
                %th= t(:name)
                %th= t(:category)
                %th= t(:amount)
                %th= t(:description)
                %th= t(:spent_on)
                %th= t(:user)
                %th= t(:actions)
            %tbody
              - @cost_query.results.each do |cost|
                %tr
                  %td= cost.name
                  %td= cost.cost_category.name
                  %td= cost.amount
                  %td= cost.description
                  %td= l(cost.spent_on)
                  %td= cost.user.try(:username)
                  %td
                    = link_to edit_cost_path(cost), title: t(:edit) do
                      %i.fa.fa-pencil.fa-fw
                    = link_to cost, method: :delete, title: t(:destroy), data: { confirm: t(:a_u_sure) } do
                      %i.fa.fa-trash-o.fa-fw

  .col-lg-12
    = paginate @cost_query.results

app/views/costs/new.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:new_cost)
.row
  .col-lg-12
    = render 'form'