config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#index'

  resource :dashboard, only: [] do
    get :sample
  end

  resources :costs, except: :show
  resources :cost_categories, except: :show
  resources :funds, except: :show
  resources :incomes, except: :show

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :charts, only: [] do
        collection do
          get :bar_month_by_category, :area_last_days_costs, :donut_category_by_last
        end
      end
    end
  end

  namespace :kodi do
    namespace :v1 do
      resources :videos, only: [:index, :show] do
        get :search, :root_directory, on: :collection
      end
    end
  end

  namespace :react do
    namespace :v1 do
      resources :audios, only: [:index] do
        get :seed, on: :collection
      end

      resources :users, only: [] do
        get :current, on: :collection
      end
    end
  end

  ActiveAdmin.routes(self)
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user

  validates_presence_of :name, :amount
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  after_action :expire_last_cost_fragments, only: [:create, :update, :destroy]

  def index
    @incomes = Income.includes(:user).order('id DESC').per_page_kaminari(params[:page])
  end

  def new
    @income = Income.new
  end

  def edit
  end

  def create
    @income = Income.new(cost_params.merge(user: current_user))

    respond_to do |format|
      if income.save
        format.html { redirect_to incomes_url, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: income }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: income.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if income.update(cost_params)
        format.html { redirect_to incomes_url, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: income }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: income.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def income
      @income ||= Income.find(params[:id])
    end
    helper_method :income

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:income).permit(
        :name,
        :amount,
        :description,
        :got_on
      )
    end
end

app/views/incomes/_form.html.haml
= simple_form_for income, defaults: { input_html: { :class => 'form-control' } } do |f|
  .row
    .col-lg-6
      = f.error_notification
      %fieldset
        = f.input :name
        = f.input :amount
        = f.input :description
        = f.input :got_on
      .actions
        = f.submit t(:save), class: 'btn btn-success'

app/views/incomes/edit.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:edit_income)
.row
  .col-lg-12
    = render 'form'

app/views/incomes/index.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:incomes)
.row.hidden-xs
  .col-lg-12
    %p.pull-right
      = link_to new_income_path, class: 'btn btn-success' do
        %i.fa.fa-plus
        = t(:add_new_income)
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading= t(:incomes_list)
      .panel-body
        .table-responsive
          %table.table
            %thead
              %tr
                %th= t(:name)
                %th= t(:amount)
                %th= t(:description)
                %th= t(:got_on)
                %th= t(:user)
                %th= t(:actions)
            %tbody
              - @incomes.each do |income|
                %tr
                  %td= income.name
                  %td= income.amount
                  %td= income.description
                  %td= l(income.got_on)
                  %td= income.user.try(:username)
                  %td
                    = link_to edit_income_path(income), title: t(:edit) do
                      %i.fa.fa-pencil.fa-fw
                    = link_to income, method: :delete, title: t(:destroy), data: { confirm: t(:a_u_sure) } do
                      %i.fa.fa-trash-o.fa-fw

  .col-lg-12
    = paginate @incomes

app/views/incomes/new.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:new_income)
.row
  .col-lg-12
    = render 'form'