config/routes.rb
Rails.application.routes.draw do
  root 'dashboards#index'

  resource :dashboard, only: [] do
    get :sample
  end

  resources :costs, except: :show
  resources :cost_categories, except: :show
  resources :funds, except: :show
  resources :incomes, except: :show

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :charts, only: [] do
        collection do
          get :bar_month_by_category, :area_last_days_costs, :donut_category_by_last
        end
      end
    end
  end

  namespace :kodi do
    namespace :v1 do
      resources :videos, only: [:index, :show] do
        get :search, :root_directory, on: :collection
      end
    end
  end

  namespace :react do
    namespace :v1 do
      resources :audios, only: [:index] do
        get :seed, on: :collection
      end

      resources :users, only: [] do
        get :current, on: :collection
      end
    end
  end

  ActiveAdmin.routes(self)
end

app/models/fund.rb
class Fund < ApplicationRecord
  CURRENCIES = ['EUR', 'RUR', 'UAH', 'USD'].freeze

  after_save :create_fund_change

  has_many :fund_changes, inverse_of: :fund, dependent: :destroy

  validates_presence_of :name, :currency

  private def create_fund_change
    if changes.key?(:amount)
      fund_changes.create(
        amount: (changes[:amount][1] - changes[:amount][0].to_i).abs,
        from: changes[:amount][0],
        to: changes[:amount][1],
        fc_type: (changes[:amount][1] - changes[:amount][0].to_i) > 0 ? :incoming : :outgoing
      )
    end
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  after_action :expire_fund_change_fragments, only: [:create, :update, :destroy]

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all
    @fund_changes = FundChange.includes(:fund).order('id DESC').per_page_kaminari(params[:page])
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if fund.save
        format.html { redirect_to funds_url, notice: 'Fund was successfully created.' }
        format.json { render :show, status: :created, location: fund }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if fund.update(fund_params)
        format.html { redirect_to funds_url, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: fund }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def fund
      @fund ||= Fund.find(params[:id])
    end
    helper_method :fund

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:name, :amount, :currency, :description)
    end
end

app/views/funds/_changes_list.html.haml
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading= t(:fund_changes_list)
      .panel-body
        .table-responsive
          %table.table
            %thead
              %tr
                %th= t(:name)
                %th= t(:amount)
                %th= t(:type)
                %th= t(:created_at)
            %tbody
              - @fund_changes.each do |change|
                %tr
                  %td= change.fund.name
                  %td= change.amount
                  %td= t("fund_changes.#{change.fc_type}")
                  %td= l(change.created_at.to_date)
.row
  .col-lg-12
    = paginate @fund_changes

app/views/funds/_form.html.haml
= simple_form_for fund, defaults: { input_html: { :class => 'form-control' } } do |f|
  .row
    .col-lg-6
      = f.error_notification
      %fieldset
        = f.input :name
        = f.input :amount
        = f.input :currency, collection: Fund::CURRENCIES, prompt: :translate
        = f.input :description
      .actions
        = f.submit t(:save), class: 'btn btn-success'

app/views/funds/_list.html.haml
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading= t(:funds_list)
      .panel-body
        .table-responsive
          %table.table
            %thead
              %tr
                %th= t(:name)
                %th= t(:amount)
                %th= t(:currency)
                %th= t(:description)
                %th= t(:actions)
            %tbody
              - @funds.each do |fund|
                %tr
                  %td= "#{fund.name} (#{fund.currency})"
                  %td= fund.amount
                  %td= fund.currency
                  %td= fund.description
                  %td
                    = link_to edit_fund_path(fund), title: t(:edit) do
                      %i.fa.fa-pencil.fa-fw
                    = link_to fund, method: :delete, title: t(:destroy), data: { confirm: t(:a_u_sure) } do
                      %i.fa.fa-trash-o.fa-fw

app/views/funds/_summary_by_currency.html.haml
.row
  .col-lg-3.col-md-6
    .panel.panel-primary
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-eur.fa-5x
          .col-xs-9.text-right
            .huge= currency_grouped_funds['EUR'] || 0
            %div EUR!
      %a{ href: '#' }
        .panel-footer
          %span.pull-left View Details
          %span.pull-right
            %i.fa.fa-arrow-circle-right
          .clearfix
  .col-lg-3.col-md-6
    .panel.panel-green
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-usd.fa-5x
          .col-xs-9.text-right
            .huge= currency_grouped_funds['USD'] || 0
            %div USD!
      %a{ href: '#' }
        .panel-footer
          %span.pull-left View Details
          %span.pull-right
            %i.fa.fa-arrow-circle-right
          .clearfix
  .col-lg-3.col-md-6
    .panel.panel-yellow
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-bitcoin.fa-5x
          .col-xs-9.text-right
            .huge= currency_grouped_funds['UAH'] || 0
            %div UAH!
      %a{ href: '#' }
        .panel-footer
          %span.pull-left View Details
          %span.pull-right
            %i.fa.fa-arrow-circle-right
          .clearfix
  .col-lg-3.col-md-6
    .panel.panel-yellow
      .panel-heading
        .row
          .col-xs-3
            %i.fa.fa-ruble.fa-5x
          .col-xs-9.text-right
            .huge= currency_grouped_funds['RUR'] || 0
            %div RUR!
      %a{ href: '#' }
        .panel-footer
          %span.pull-left View Details
          %span.pull-right
            %i.fa.fa-arrow-circle-right
          .clearfix

app/views/funds/edit.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:edit_fund)
.row
  .col-lg-12
    = render 'form'

app/views/funds/index.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:funds)
.row
  .col-lg-12
    %p.pull-right
      = link_to new_fund_path, class: 'btn btn-success' do
        %i.fa.fa-plus
        = t(:add_new_fund)

= cache 'fund_change.funds.index' do
  = render 'summary_by_currency'
  = render 'list'

= render 'changes_list'

app/views/funds/new.html.haml
.row
  .col-lg-12
    %h2.page-header= t(:new_fund)
.row
  .col-lg-12
    = render 'form'